#import "./component-content-text.gql"
#import "./component-content-image.gql"
#import "./component-content-button.gql"
#import "./component-section-slideshow.gql"
#import "./component-section-facts.gql"
#import "./component-section-gallery-slideshow.gql"
#import "./component-section-blackboard-slideshow.gql"
#import "./component-home-news.gql"
#import "./component-student-section-student-quote.gql"
#import "./component-section-blog-slideshow.gql"
#import "./component-section-iframe.gql"
#import "./component-section-mensa-max.gql"
#import "./component-section-podcast-episode.gql"

fragment BlogEntryDetailFragment on BlogEntry {
  __typename
  id
  title
  slug
  created_at
  updated_at
  published_at
  author
  blog_category {
    slug
    name
  }
  content {
    __typename
    # Content sections
    ... on ComponentContentText {
      ...ComponentContentTextFragment
    }
    ... on ComponentContentImage {
      ...ComponentContentImageFragment
    }
    ... on ComponentContentButton {
      ...ComponentContentButtonFragment
    }
    # Other sections
    ... on ComponentSectionSlideshow {
      ...ComponentSectionSlideshowFragment
    }
    ... on ComponentSectionFacts {
      ...ComponentSectionFactsFragment
    }
    ... on ComponentHomeNews {
      ...ComponentHomeNewsFragment
    }
    ... on ComponentContentButton {
      ...ComponentContentButtonFragment
    }
    ... on ComponentSectionGallerySlideshow {
      ...ComponentSectionGallerySlideshowFragment
    }
    ... on ComponentSectionBlackboardSlideshow {
      ...ComponentSectionBlackboardSlideshowFragment
    }
    ... on ComponentStudentSectionStudentQuote {
      ...ComponentStudentSectionStudentQuoteFragment
    }
    ... on ComponentStudentSectionStudentQuote {
      ...ComponentStudentSectionStudentQuoteFragment
    }
    ... on ComponentSectionBlogSlideshow {
      ...ComponentSectionBlogSlideshowFragment
    }
    ... on ComponentSectionIFrame {
      ...ComponentSectionIFrameFragment
    }
    ...on ComponentSectionMensaMax {
      ...ComponentSectionMensaMaxFragment
    }
    ... on ComponentSectionPodcastEpisode {
      ...ComponentSectionPodcastEpisodeFragment
    }
  }
}
