#import "./component-content-text.gql"
#import "./component-content-image.gql"
#import "./component-content-button.gql"

#import "./component-section-podcast-episode.gql"

# Shorter version if BlogEntryDetailFragment, e.g. for news, search results and blog post overview
fragment BlogEntryBasicFragment on BlogEntry {
  __typename
  id
  title
  slug
  created_at
  updated_at
  published_at
  author
  blog_category {
    slug
    name
  }
  content {
    __typename
    # Content sections
    ... on ComponentContentText {
      ...ComponentContentTextFragment
    }
    ... on ComponentContentImage {
      ...ComponentContentImageFragment
    }
    # ... on ComponentContentButton {
    #   ...ComponentContentButtonFragment
    # }
    # Other sections we can extract content (like texts and images) from
    ... on ComponentSectionPodcastEpisode {
      ...ComponentSectionPodcastEpisodeFragment
    }
  }
}
