#import "./blog-entry-detail.gql"

fragment BlogCategoryDetailFragment on BlogCategory {
  __typename
  id
  created_at
  updated_at
  name
  slug
  blog_entries {
    ...on BlogEntry {
      ...BlogEntryDetailFragment
    }
  }
}