#import "./color.gql"

fragment ComponentSlideshowEntryPageFragment on ComponentSlideshowSlideshowEntryPage {
  id
  image {
    formats
  }
  subtitle
  label
  color {
    ...ColorFragment
  }
  page {
    __typename
    slug
  }
}
