#import "./color.gql"
#import "./image.gql"

fragment ComponentSlideshowEntryBlogFragment on ComponentSlideshowSlideshowEntryBlog {
  id
  image {
    ...ImageFragment
  }
  subtitle
  label
  color {
    ...ColorFragment
  }
  post {
    __typename
    slug
  }
}
