#import "./school-subject-basic.gql"
#import "./image.gql"

fragment ComponentBlackboardSlideFragment on ComponentBlackboardSlide {
  id
  school_subject {
    ... on Subject {
      ...SchoolSubjectBasicFragment
    }
  }
  image {
    ...ImageFragment
  }
}
