#import "./color.gql"

fragment ComponentSlideshowEntryBlogFragment on ComponentSlideshowSlideshowEntryBlog {
  id
  image {
    formats
  }
  subtitle
  label
  color {
    ...ColorFragment
  }
  post {
    __typename
    slug
  }
}
