#import "./color.gql"
#import "./image.gql"

fragment ComponentSlideshowEntryFragment on ComponentSlideshowSlideshowEntry {
  id
  image {
    ...ImageFragment
  }
  subtitle
  color {
    ...ColorFragment
  }
}
