fragment ComponentSectionBlackboardSlideshowFragment on ComponentSectionBlackboardSlideshow {
  id
  subjects {
    ... on Subject {
      title
      slug
      blackboard_image {
        ...ImageFragment
      }
    }
  }
  disabled
}
