#import "./navigation-link.gql"
#import "./color.gql"
#import "./alignment.gql"

fragment ComponentContentButtonFragment on ComponentContentButton {
  id
  label
  alignment {
    ...AlignmentFragment
  }
  color {
    ...ColorFragment
  }
  link {
    ...NavigationLinkFragment
  }
  disabled
}
