#import "./blog-category-basic.gql"
#import "./color.gql"

fragment ComponentSectionBlogSlideshowFragment on ComponentSectionBlogSlideshow {
  id
  limit
  blog {
    ... on BlogCategory {
      ...BlogCategoryBasicFragment
    }
  }
  style
  color {
    ...ColorFragment
  }
  disabled
}
