#import "./color.gql"
#import "./image.gql"

fragment ComponentSlideshowEntryPageFragment on ComponentSlideshowSlideshowEntryPage {
  id
  image {
    ...ImageFragment
  }
  subtitle
  label
  color {
    ...ColorFragment
  }
  page {
    __typename
    slug
  }
}
