#import "./podcast-episode-basic.gql"

fragment ComponentSectionPodcastEpisodeFragment on ComponentSectionPodcastEpisode {
  __typename
  podcast_episode {
    ...PodcastEpisodeBasicFragment
  }
  disabled
}
