#import "./school-subject-detail.gql"

fragment ComponentSectionBlackboardSlideshowFragment on ComponentSectionBlackboardSlideshow {
  id
  subjects {
    ... on SchoolSubject {
      ...SchoolSubjectDetailFragment
    }
  }
}
