fragment ComponentSlideshowEntryPageFragment on ComponentSlideshowSlideshowEntryPage {
  id
  image {
    formats
  }
  subtitle
  label
  color {
    color
  }
  page {
    __typename
    slug
  }
}
