fragment ComponentSlideshowEntryBlogFragment on ComponentSlideshowSlideshowEntryBlog {
  id
  image {
    formats
  }
  subtitle
  label
  color {
    color
  }
  post {
    __typename
    slug
  }
}
