#import "./component-gallery-image.gql"
#import "./color.gql"

fragment GalleryFragment on Gallery {
  id
  slug
  title
  images {
    ... on ComponentGalleryImage {
      ...ComponentGalleryImageFragment
    }
  }
  style
  color {
    ...ColorFragment
  }
}