fragment NavigationLinkFragment on NavigationLink {
  id
  title
  type {
      __typename
    ... on ComponentLinkTypeWeb {
      URL
    }
    ... on ComponentLinkTypeStrapi {
      URL
    }
    ... on ComponentLinkTypePage {
      page {
        title
        slug
      }
    }
    ... on ComponentLinkTypeSchoolSubject {
      school_subject {
        title
        slug
      }
    }
    ... on ComponentLinkTypePost {
      post {
        title
        slug
      }
    }
    ... on ComponentLinkTypeBlog {
      blog {
        name
        slug
      }
    }
    ... on ComponentLinkTypeMediaCenter {
      mediaCenter {
        title
        slug
      }
    }
    ... on ComponentLinkTypeGallery {
      gallery {
        title
        slug
      }
    }
    ... on ComponentLinkTypePodcast {
      podcastEpisode {
        title
        slug
      }
    }
    ... on ComponentLinkTypeWorkingGroup {
      working_group {
        title
        slug
      }
    }
  }
}
