#import "./component-content-text.gql"
#import "./component-content-image.gql"
#import "./component-content-button.gql"
#import "./blog-entry-basic.gql"
#import "./component-section-slideshow.gql"
#import "./component-section-gallery-slideshow.gql"

fragment PageDetailFragment on Page {
  __typename
  id
  created_at
  updated_at
  title
  slug
  calendar_key
  assets {
    ... on ComponentSidebarAssets {
      file {
        url
      }
      name
    }
  }

  blog_entries {
    ...BlogEntryBasicFragment
  }

  content {
    __typename
    # Content sections
    ... on ComponentContentText {
      ...ComponentContentTextFragment
    }
    ... on ComponentContentImage {
      ...ComponentContentImageFragment
    }
    ... on ComponentContentButton {
      ...ComponentContentButtonFragment
    }
    # Other sections
    ... on ComponentSectionSlideshow {
      ...ComponentSectionSlideshowFragment
    }
    ... on ComponentSectionGallerySlideshow {
      ...ComponentSectionGallerySlideshowFragment
    }
  }
}