#import "./school-subject-basic.gql"
#import "./image.gql"

fragment PodcasterDetailFragment on Podcaster {
  id
  slug
  name
  biography
  image {
    ...ImageFragment
  }
  podcast_episodes {
    ...PodcastEpisodeBasicFragment
  }
}
