#import "./podcast-episode-upload-file.gql"
#import "./image.gql"
#import "./component-podcast-chapters.gql"
#import "./podcaster-basic.gql"

fragment PodcastEpisodeDetailFragment on PodcastEpisode {
  __typename
  id
  title
  subtitle
  slug
  content {
    ... on UploadFile {
      ...PodcastEpisodeUploadFileFragment
    }
  }
  pubDate
  published_at
  description
  image {
    ...ImageFragment
  }
  explicit
  episode
  season
  type
  block
  chapters {
    ...ComponentPodcastChaptersFragment
  }
  contributors {
    ...PodcasterBasicFragment
  }
}
