#import "./teacher-basic.gql"

#import "./component-content-text.gql"
#import "./component-content-image.gql"
#import "./component-content-button.gql"
#import "./component-content-download-button.gql"
#import "./component-section-slideshow.gql"
#import "./component-section-facts.gql"
#import "./component-section-gallery-slideshow.gql"
#import "./component-section-blackboard-slideshow.gql"
#import "./component-home-news.gql"
#import "./component-student-section-student-quote.gql"
#import "./component-section-blog-slideshow.gql"
#import "./component-section-iframe.gql"
#import "./component-section-mensa-max.gql"
#import "./component-section-podcast-episode.gql"
#import "./component-section-latest-podcast-episode.gql"

fragment SchoolSubjectDetailFragment on Subject {
  __typename
  id
  slug
  title
  created_at
  updated_at
  teachers {
    ... on Teacher {
      ...TeacherBasicFragment
    }
  }
  content {
    __typename
    # Content sections
    ... on ComponentContentText {
      ...ComponentContentTextFragment
    }
    ... on ComponentContentImage {
      ...ComponentContentImageFragment
    }
    ... on ComponentContentButton {
      ...ComponentContentButtonFragment
    }
    ... on ComponentContentDownloadButton {
      ...ComponentContentDownloadButtonFragment
    }
    # Other sections
    ... on ComponentSectionSlideshow {
      ...ComponentSectionSlideshowFragment
    }
    ... on ComponentSectionFacts {
      ...ComponentSectionFactsFragment
    }
    ... on ComponentHomeNews {
      ...ComponentHomeNewsFragment
    }
    ... on ComponentSectionGallerySlideshow {
      ...ComponentSectionGallerySlideshowFragment
    }
    ... on ComponentSectionBlackboardSlideshow {
      ...ComponentSectionBlackboardSlideshowFragment
    }
    ... on ComponentStudentSectionStudentQuote {
      ...ComponentStudentSectionStudentQuoteFragment
    }
    ... on ComponentSectionBlogSlideshow {
      ...ComponentSectionBlogSlideshowFragment
    }
    ... on ComponentSectionIFrame {
      ...ComponentSectionIFrameFragment
    }
    ...on ComponentSectionMensaMax {
      ...ComponentSectionMensaMaxFragment
    }
    ... on ComponentSectionPodcastEpisode {
      ...ComponentSectionPodcastEpisodeFragment
    }
    ... on ComponentSectionLatestPodcastEpisode {
      ...ComponentSectionLatestPodcastEpisodeFragment
    }
  }
}