#import "./school-subject-basic.gql"
#import "./working-group-basic.gql"
#import "./image.gql"

#import "./component-attachment-assets.gql"

fragment TeacherDetailFragment on Teacher {
  id
  slug
  name
  biography
  image {
    ...ImageFragment
  }
  subjects {
    ... on Subject {
      ...SchoolSubjectBasicFragment
    }
  }
  working_groups {
    ... on WorkingGroup {
      ...WorkingGroupBasicFragment
    }
  }
  assets {
    ... on ComponentAttachmentAssets {
      ...ComponentAttachmentAssetsFragment
    }
  }
}
