#import "./school-subject-basic.gql"
#import "./image.gql"

fragment TeacherDetailFragment on Teacher {
  id
  slug
  name
  first_name
  biography
  image {
    ...ImageFragment
  }
  subjects {
    ... on Subject {
      ...SchoolSubjectBasicFragment
    }
  }
}
