#import "../fragments/blog-category-detail.gql"

query blogCategoriesDetailBySlugs ($slugs: [String]!, $limit: Int!, $start: Int!) {
  blogCategories(sort:"created_at:desc", start: $start, limit: $limit, where: { slug: $slugs }) {
    ...BlogCategoryDetailFragment
  }
}
