#import "../fragments/navigation-link.gql"
#import "../fragments/image.gql"

query footer {
  footer {
    map_image {
      ...ImageFragment
    }
  	map_link
    contact_info
    link {
      navigation_link {
        ...NavigationLinkFragment
      }
    }
  }
}