#import "../fragments/gallery.gql"

query galleryBySlugs ($slugs: [String]!, $limit: Int!, $start: Int!) {
  galleries(start: $start, limit: $limit, where: { slug: $slugs }) {
    ...GalleryFragment
  }
} 
