#import "../fragments/podcast-episode-basic.gql"

query podcastEpisodesBasicBySlugs ($slugs: [String]!, $limit: Int!, $start: Int!) {
  podcastEpisodes(sort:"pubDate:desc", start: $start, limit: $limit, where: { slug: $slugs }) {
    ...PodcastEpisodeBasicFragment
  }
}
