#import "../fragments/podcast-episode-detail.gql"

query podcastEpisodesDetailBySlugs ($slugs: [String]!, $limit: Int!, $start: Int!) {
  podcastEpisodes(sort:"pubDate:desc", start: $start, limit: $limit, where: { slug: $slugs }) {
    ...PodcastEpisodeDetailFragment
  }
}
