#import "./component-section-slideshow.gql"
#import "./component-content-text.gql"
#import "./component-content-image.gql"
#import "./component-section-gallery-slideshow.gql"

fragment BlogEntryFragment on BlogEntry {
  id
  title
  slug
  created_at
  updated_at
  published_at
  blog_category {
    name
  }
  content {
    __typename
    ... on ComponentSectionSlideshow {
      ...ComponentSectionSlideshowFragment
    }
    ... on ComponentSectionGallerySlideshow {
      ...ComponentSectionGallerySlideshowFragment
    }
    ... on ComponentContentImage {
      ...ComponentContentImageFragment
    }
    ... on ComponentContentText {
      ...ComponentContentTextFragment
    }
  }
}
