#import "../fragments/component-content-image.gql"

fragment BlogEntryFragment on BlogEntry {
  id
  title
  slug
  created_at
  updated_at
  published_at
  blog_category {
    name
  }
  content {
    __typename
    ... on ComponentContentImage {
      ...ComponentContentImageFragment
    }
    ... on ComponentContentText {
      id
      text
    }
  }
}
