#import "./navigation-link.gql"

fragment MenuFragment on Menu {
  entries: navigation_level_entry {
    id
    parent {
      id
    }
    title
    hideInSidebar
    navigation_link {
      ...NavigationLinkFragment
    }
  }
}
