#import "./blog-entry.gql"

fragment PageFragment on Page {
  id
  created_at
  updated_at
  title
  slug
  calendar_key
  assets {
    ... on ComponentSidebarAssets {
      file {
        url
      }
      name
    }
  }

  blog_entries {
    ...BlogEntryFragment
  }

  content {
    __typename
    ... on ComponentContentImage {
      id
      caption
      image {
        id
        created_at
        updated_at
        name
        alternativeText
        caption
        width
        height
        formats
        hash
        ext
        mime
        size
        url
        previewUrl
        provider
        provider_metadata
      }
    }
    ... on ComponentContentText {
      id
      text
    }
  }
}