#import "./blog-entry-basic.gql"
#import "./component-section-slideshow.gql"
#import "./component-content-text.gql"
#import "./component-content-image.gql"
#import "./component-section-gallery-slideshow.gql"

fragment PageFragment on Page {
  __typename
  id
  created_at
  updated_at
  title
  slug
  calendar_key
  assets {
    ... on ComponentSidebarAssets {
      file {
        url
      }
      name
    }
  }

  blog_entries {
    ...BlogEntryBasicFragment
  }

  content {
    __typename
    ... on ComponentSectionSlideshow {
      ...ComponentSectionSlideshowFragment
    }
    ... on ComponentSectionGallerySlideshow {
      ...ComponentSectionGallerySlideshowFragment
    }
    ... on ComponentContentImage {
      ...ComponentContentImageFragment
    }
    ... on ComponentContentText {
      ...ComponentContentTextFragment
    }
  }
}