#import "./component-section-slideshow.gql"
#import "./component-content-text.gql"
#import "./component-content-image.gql"
#import "./component-section-gallery-slideshow.gql"
#import "./teacher-basic.gql"

fragment SchoolSubjectDetailFragment on Subject {
  __typename
  id
  slug
  title
  created_at
  updated_at
  teachers {
    ... on Teacher {
      ...TeacherBasicFragment
    }
  }
  content {
    __typename
    ... on ComponentSectionSlideshow {
      ...ComponentSectionSlideshowFragment
    }
    ... on ComponentSectionGallerySlideshow {
      ...ComponentSectionGallerySlideshowFragment
    }
    ... on ComponentContentImage {
      ...ComponentContentImageFragment
    }
    ... on ComponentContentText {
      ...ComponentContentTextFragment
    }
  }
}