#import "./component-content-image.gql"
#import "./component-content-text.gql"

fragment SchoolSubjectFragment on Subject {
  id
  created_at
  updated_at
  title
  slug
  content {
    __typename
    ... on ComponentContentImage {
      ...ComponentContentImageFragment
    }
    ... on ComponentContentText {
      ...ComponentContentTextFragment
    }
  }
}