#import "../fragments/blog-entry.gql"

query blogEntriesBySlugs ($slugs: [String]!) {
  blogEntries(sort:"created_at:desc", start: 0, limit: 50, where: { slug: $slugs }) {
    ...BlogEntryFragment
  }
}
