# Write your query or mutation here
query {
  blogEntries(start: 0, limit: 50) {
    id,
    created_at,
    updated_at,
    Title,
    Content {
      __typename,
    }
    slug,
    published_at,
  }
}