query footer {
  footer {
    map_image {
      url
      alternativeText
    }
  	map_link
    contact_info
    link {
      navigation_link {
        title
        type {
          __typename
          ... on ComponentLinkTypePage {
            page {
              slug
            }
          }
          ... on ComponentLinkTypeWeb {
            URL
          }
          ... on ComponentLinkTypePost {
            post {
              slug
            }
          }
        }
      }
    }
  }
}