
#import "../fragments/component-section-facts.gql"
#import "../fragments/component-content-text.gql"
#import "../fragments/component-content-image.gql"

query homeSections {
  home {
    sections {
      __typename
      ... on ComponentSectionSlideshow {
        slideshow {
          id
        }
      }
      ... on ComponentSectionFacts {
        ...ComponentSectionFactsFragment
      }
      ... on ComponentHomeNews {
        amount
      }
      ... on ComponentContentText {
        ...ComponentContentTextFragment
      }
      ... on ComponentContentImage {
        ...ComponentContentImageFragment
      }
    }
  }
}
