# Write your query or mutation here
query HomeSections {
  home {
    sections {
      __typename
      ... on ComponentSectionSlideshow {
        slideshow {
          id
        }
      }
      ... on ComponentSectionFacts {
        facts {
          number
          title
          subtitle
        }
      }
      ... on ComponentContentText {
        text
      }
      ... on ComponentContentImage {
        image {
          formats
        }
        caption
      }
    }
  }
}
