#import "../fragments/blog-entry-basic.gql"

query News($amount: Int!) {
  blogEntries(sort:"created_at:desc", limit: $amount) {
    ...BlogEntryBasicFragment
  }
  # maybe also add pages with specific attribute later
  # pages(sort:"created_at:desc", limit: 2, where:"") {
  #  created_at
  # }
} 